apiVersion: v1
kind: Service
metadata:
  name: http20160813-1
  labels:
    app: http
    tier: frontend
    version: v20160813-1
spec:
  type: LoadBalancer
  loadBalancerIP: 104.155.206.50
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: http
    tier: frontend
