apiVersion: v1
kind: Service
metadata:
  name: http-us-east1
  labels:
    app: redirect
    tier: frontend
    version: http-us-east1
spec:
  type: LoadBalancer
  loadBalancerIP: 104.196.187.99
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: redirect
    tier: frontend
