apiVersion: v1
kind: Service
metadata:
  name: r80-us-west1
  labels:
    app: redirect
    tier: frontend
    version: r80-us-west1
spec:
  type: LoadBalancer
  loadBalancerIP: 104.198.101.141
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: redirect
    tier: frontend
