apiVersion: v1
kind: ReplicationController
metadata:
  name: redirect20160814-1
  labels:
    state: serving
    tier: frontend
    version: redirect20160814-1
spec:
  replicas: 3
  selector:
    app: redirect
    tier: frontend
    version: redirect20160814-1
  template:
    metadata:
      name: redirect
      labels:
        app: redirect
        tier: frontend
        version: redirect20160814-1
    spec:
      volumes: null
      containers:
      - name: redirect
        image: minecraftly/redirect:latest
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
