apiVersion: v1
kind: Service
metadata:
  name: redirect-tcp-asia-east1
  labels:
    app: redirect
    tier: frontend
    version: redirect-tcp-asia-east1
spec:
  type: LoadBalancer
  loadBalancerIP: 104.155.206.50
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: redirect
    tier: frontend
